runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "18"

manual_scaling:
  instances: 1

beta_settings:
  cloud_sql_instances: "ivory-infinity-441116-s0:asia-southeast1:db-challenge-binar"
