runtime: nodejs
env: flex

runtime_config:
  operating_system: "ubuntu22"
  runtime_version: "18"

manual_scaling:
  instances: 1

includes:
  - env.yaml

beta_settings:
  cloud_sql_instances: ${CLOUD_SQL_INSTANCES}
